server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/product/**

            - id: product-service-category
              uri: lb://product-service
              predicates:
                  - Path=/api/category/**

            - id: media-service
              uri: lb://media-service
              predicates:
                - Path=/api/media/**

            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**,/api/auth/**,/oauth2/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/order/**

            - id: order-service-cart
              uri: lb://order-service
              predicates:
                - Path=/api/cart/**

