spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083
