spring.application.name=product-service

server.port=8081

#DB configuration
spring.datasource.url= jdbc:mysql://localhost:3306/product_db
spring.datasource.username=root
spring.datasource.password=ashum

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

