server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
